// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMluew050qAduSJXvnjQsnnEAwl37aKm0',
    appId: '1:607570398022:web:3871445cd52f024e20b347',
    messagingSenderId: '607570398022',
    projectId: 'mpkps-c7d4f',
    authDomain: 'mpkps-c7d4f.firebaseapp.com',
    storageBucket: 'mpkps-c7d4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ4pUHJm6MDS7nwQaoPhAlKzqFLCmAfRk',
    appId: '1:607570398022:android:fdee0cc05dd1397820b347',
    messagingSenderId: '607570398022',
    projectId: 'mpkps-c7d4f',
    storageBucket: 'mpkps-c7d4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZO1aKcOYssgCOFDDAWUMMgxMYF5D27k',
    appId: '1:607570398022:ios:1720db550622acaf20b347',
    messagingSenderId: '607570398022',
    projectId: 'mpkps-c7d4f',
    storageBucket: 'mpkps-c7d4f.appspot.com',
    iosBundleId: 'com.example.mpkps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ZO1aKcOYssgCOFDDAWUMMgxMYF5D27k',
    appId: '1:607570398022:ios:7ed4f33cddfda3c620b347',
    messagingSenderId: '607570398022',
    projectId: 'mpkps-c7d4f',
    storageBucket: 'mpkps-c7d4f.appspot.com',
    iosBundleId: 'com.example.mpkps.RunnerTests',
  );
}
